### PR TITLE
Add support for polymorphic associations for has_many_aggregate

### PR DESCRIPTION
**Pull request by sideshowdave7**
This adds support for has_many_aggregate against polymorphic associations.  Previously the query lacked a where condition on the polymorphic type and so would give bad counts with polymorphic associations with multiple types on the other end of the association.

### CODE REVIEW

**Comment by doliveirakn** [comment]
@sideshowdave7 Do you have a spec you can add for this change?

**Comment by sideshowdave7** [comment]
I'll work on a spec for this.

**Comment by sideshowdave7** [comment]
@doliveirakn I've added a test case where this used to break and it's passing.  I noticed there is an existing broken test, I did verify that it's broken on the current master branch and I didn't introduce a regression.

**Comment by doliveirakn** [comment]
@sideshowdave7 Thanks for the spec!

I have fixed up the failing spec and merged in your changes. I released a new version of the gem `0.2.0` that includes your changes.

**Pull request merged**
